"""Add Row-Level Security policies

Revision ID: 0f5a2883880f
Revises: a9d1bf9b779e
Create Date: 2025-06-21 23:47:10.484144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5a2883880f'
down_revision: Union[str, Sequence[str], None] = 'a9d1bf9b779e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Enable RLS for all relevant tables
    op.execute("ALTER TABLE companies ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE utm_links ENABLE ROW LEVEL SECURITY;")
    
    # Force RLS for table owners
    op.execute("ALTER TABLE companies FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE users FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE campaigns FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE utm_links FORCE ROW LEVEL SECURITY;")

    # Create RLS policies
    op.execute("""
        CREATE POLICY company_isolation_policy ON companies
        FOR ALL
        USING (id = current_setting('app.current_company_id')::uuid);
    """)

    op.execute("""
        CREATE POLICY user_isolation_policy ON users
        FOR ALL
        USING (company_id = current_setting('app.current_company_id')::uuid);
    """)

    op.execute("""
        CREATE POLICY campaign_isolation_policy ON campaigns
        FOR ALL
        USING (company_id = current_setting('app.current_company_id')::uuid);
    """)

    op.execute("""
        CREATE POLICY utm_link_isolation_policy ON utm_links
        FOR ALL
        USING (EXISTS (
            SELECT 1
            FROM campaigns
            WHERE campaigns.id = utm_links.campaign_id
              AND campaigns.company_id = current_setting('app.current_company_id')::uuid
        ));
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop RLS policies
    op.execute("DROP POLICY IF EXISTS company_isolation_policy ON companies;")
    op.execute("DROP POLICY IF EXISTS user_isolation_policy ON users;")
    op.execute("DROP POLICY IF EXISTS campaign_isolation_policy ON campaigns;")
    op.execute("DROP POLICY IF EXISTS utm_link_isolation_policy ON utm_links;")

    # Disable RLS
    op.execute("ALTER TABLE companies DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE users DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE campaigns DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE utm_links DISABLE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###
