"""add demographics and interests to campaigns

Revision ID: 931cd2c57972
Revises: xxxxxxxxxxxx
Create Date: 2025-06-25 10:36:55.842295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931cd2c57972'
down_revision: Union[str, Sequence[str], None] = 'xxxxxxxxxxxx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'MEMBER', 'VIEWER', name='userrole',create_type=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='invitestatus'), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_table('team_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_memberships_id'), 'team_memberships', ['id'], unique=False)
    op.add_column('campaigns', sa.Column('demographics', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('interests', sa.String(), nullable=True))
    op.drop_index(op.f('idx_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('idx_utm_links_fulltext_gin'), table_name='utm_links', postgresql_using='gin')
    op.drop_index(op.f('idx_utm_links_generated_url'), table_name='utm_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_utm_links_generated_url'), 'utm_links', ['generated_url'], unique=False)
    op.create_index(op.f('idx_utm_links_fulltext_gin'), 'utm_links', [sa.literal_column("to_tsvector('english'::regconfig, (((COALESCE(utm_source, ''::character varying)::text || ' '::text) || COALESCE(utm_medium, ''::character varying)::text) || ' '::text) || COALESCE(utm_content, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.drop_column('campaigns', 'interests')
    op.drop_column('campaigns', 'demographics')
    op.drop_index(op.f('ix_team_memberships_id'), table_name='team_memberships')
    op.drop_table('team_memberships')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
